---
common:
  table_prefix: newsletter_
  designs_path: <%= "#{Rails.root}/newsletters" %>
  site_url: http://ireach.dev
  asset_path: newsletter_assets
  #designs_require_authentication: true
  #newsletters_require_authentication: true
